### ISSUE TITLE
Mine shorings getting used up if same shoring wants to be used by another

### ISSUE THREAD

**Issue by SickBoySB** [SickBoySB/cecommpatch#23]
Need more info on this, not sure of the exact circumstances/effect.

**Comment by SickBoySB** [comment]
https://community.gaslampgames.com/threads/mine-shoring-supplies-reduced-by-one-for-each-locked-attempt.18666/

**Comment by Naffarin** [comment]
change scripts\gameobjects\FSM\citizen\mine.fsm to 
mine = {
	["start"] = function(state,tag,name)
		
		-- check if building is occupied.
		local module_tags = query(tag.target,"getTags")[1]
		if module_tags.occupied then
			--printl("DAVID", state.AI.name .. " aborting mine.fsm due to mine being occupied")
			return "abort", true
		end
		-- check if building has supplies at all; abort if not. Consume if yes.
		local building = query(tag.target,"getParentBuilding")[1]
		local building_tags = false
		if building then
			building_tags = query(building,"getTags")[1]
[...]
The occupation check needs to be done before the supplies are consumed in (originally) line 19 send(building,"consumeSupplies",1,1)
