### ISSUE TITLE
Beer/whiskey doesn't trigger "Bottoms Up" achievement

### ISSUE THREAD

**Issue by SickBoySB** [SickBoySB/cecommpatch#24]

**Comment by Naffarin** [comment]
As the exorcism fix 
Change scripts\gameobjects\FSM\citizen\pub_get_drink_from_vat.fsm, add send("gameSession", "setSteamAchievement", "bottomsUp") after line 21 send("gameSession", "setSessionBool", "bottomsUp", true)

(Untested)

**Comment by SickBoySB** [comment]
I don't think that file is actually used anymore. All my tests show no results whatsoever from it, even when trying to print to the console.txt. There are a few other pub-related FSM files though, so going to play with those and see where it might work. pub_drink_in_chair is looking promising.

**Comment by SickBoySB** [comment]
I've been able to fix this, but with a slight hitch. The count of booze served is actually stored now, and the achievement will trigger when it should. BUT... there is no way to fix the progress of the achievement, as the Steam stat variable is wrong and not stored anywhere.

But hey, at least it works now :)
