### ISSUE TITLE
Exorcisms don't trigger "Who you gonna call" achievement

### ISSUE THREAD

**Issue by SickBoySB** [SickBoySB/cecommpatch#25]

**Comment by Naffarin** [comment]
Should be fixable in scripts\gameobjects\FSM\citizen\vicar_confront_spectre.fsm by adding send("gameSession", "setSteamAchievement", "whoYouGonnaCall") after line 119 send("gameSession", "setSessionBool", "whoYouGonnaCall", true)

(Untested)

**Comment by SickBoySB** [comment]
The fix is likely similar to the Bottoms Up fix (ie no Steam stat progression, but ultimately a working achievement) but I'm finding it difficult to setup a test scenario.

**Comment by SickBoySB** [comment]
And done. Same general idea as the Bottoms Up fix. Swapped things around a bit, and added the functionality to the Eerie Spectres event, which will add spectre banishment in bulk... every mass-exorcised spectre is counted. I'm not actually sure vicar_confront_spectre is used, but it's a really difficult one to test because of how spectres work. At the very least the Eerie Spectres event will lead to success.
