### ISSUE TITLE
"No door" alert when confirming barracks blueprint

### ISSUE THREAD

**Issue by SickBoySB** [SickBoySB/cecommpatch#30]
Dev mentioned elsewhere that it was caused by "new ammo amounts code"

**Comment by Naffarin** [comment]
Propably caused by barracks,go calling recalculateQuality in line 12 due to call to barracks_reset_supply_text in setWeaponLoadout which is called in Create.

Fixable by adding a 
if not state.completed then
	return
end in  barracks_reset_supply_text at the beginning.
(Untested)
