### ISSUE TITLE
Spawn MK1 Steam Knights fail

### ISSUE THREAD

**Issue by Naffarin** [SickBoySB/cecommpatch#59]
https://community.gaslampgames.com/threads/steam-knight-manufactory-wont-manufacture-steam-knights.20978/

Change C:\Program Files (x86)\Steam\steamapps\common\Clockwork Empires\scripts\entity\vehicle.edb in line 34 from name = "SK-1 Steam Knight", to name = "MK-1 Steam Knight",

**Comment by SickBoySB** [comment]
This should already be fixed. Is it still occurring in the v1 branch?

**Comment by Naffarin** [comment]
Sorry...didn't see the vehicle.edb change
